# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a682097c3f3e2ab4544b1a4df26a4bd9af9272a9b75fa0abc790ae0e4cdc54c161af15b9897d8a723e256ed779f98cf563fbba639a73dd0f355e889b0e5a167

test:
  secret_key_base: 45bf6eec170f2b4598f92419ac1467b607aa7d0da4cbad5eab07a8f41ae96b3ee52ec0c3483961e3f4661b2da4820d1e3bd0831424a9fd45eadcc50ca6789213

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
